"""Add reps and sets to scores model

Revision ID: 00e4322a352f
Revises: 91e2179b2485
Create Date: 2025-07-27 14:29:20.525399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e4322a352f'
down_revision: Union[str, Sequence[str], None] = '91e2179b2485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('reps', sa.Integer(), nullable=True))
    op.add_column('scores', sa.Column('sets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'sets')
    op.drop_column('scores', 'reps')
    # ### end Alembic commands ###
