"""Add id to routine_submission

Revision ID: 02b778152ada
Revises: 276bbb4cee53
Create Date: 2025-07-19 17:12:03.537914

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02b778152ada"
down_revision: Union[str, Sequence[str], None] = "276bbb4cee53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routine_submission",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("routine_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("duration", sa.Interval(), nullable=True),
        sa.Column("completion_timestamp", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["routine_id"],
            ["routines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        op.f("routine_scenario_submission_routine_id_fkey"),
        "routine_scenario_submission",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "routine_scenario_submission",
        "routine_submission",
        ["routine_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "routine_scenario_submission", type_="foreignkey")
    op.create_foreign_key(
        op.f("routine_scenario_submission_routine_id_fkey"),
        "routine_scenario_submission",
        "routines",
        ["routine_id"],
        ["id"],
    )
    op.drop_table("routine_submission")
    # ### end Alembic commands ###
