"""Add sets and reps to routine_scenario

Revision ID: 1612bc0dc4c9
Revises: d01eca8fff87
Create Date: 2025-07-07 12:24:03.918332

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1612bc0dc4c9"
down_revision: Union[str, Sequence[str], None] = "d01eca8fff87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routine_scenario_association", sa.Column("sets", sa.Integer(), nullable=False)
    )
    op.add_column(
        "routine_scenario_association", sa.Column("reps", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "routine_scenario_association",
        "routine_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "routine_scenario_association",
        "scenario_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "routine_scenario_association",
        "scenario_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "routine_scenario_association",
        "routine_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_column("routine_scenario_association", "reps")
    op.drop_column("routine_scenario_association", "sets")
    # ### end Alembic commands ###
