"""Add duration and completion timestamp to routine_submission

Revision ID: 276bbb4cee53
Revises: 9a7ed9802a71
Create Date: 2025-07-18 08:50:26.488756

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "276bbb4cee53"
down_revision: Union[str, Sequence[str], None] = "9a7ed9802a71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routine_submission", sa.Column("duration", sa.Interval(), nullable=True)
    )
    op.add_column(
        "routine_submission",
        sa.Column("completion_timestamp", sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routine_submission", "completion_timestamp")
    op.drop_column("routine_submission", "duration")
    # ### end Alembic commands ###
