"""next change

Revision ID: 27dcd007108a
Revises: 80e1c2982a5f
Create Date: 2025-10-14 14:05:27.021766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dcd007108a'
down_revision: Union[str, Sequence[str], None] = '80e1c2982a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bodyweight_calibrations_scenario_id'), 'bodyweight_calibrations', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_personal_best_events_user_created_at'), table_name='personal_best_events')
    op.create_index(op.f('ix_personal_best_events_id'), 'personal_best_events', ['id'], unique=False)
    op.drop_constraint(op.f('uq_quest_templates_code'), 'quest_templates', type_='unique')
    op.drop_constraint(op.f('fk_routines_source_routine_id_routines'), 'routines', type_='foreignkey')
    op.drop_column('routines', 'source_routine_id')
    op.drop_index(op.f('ix_user_quests_status'), table_name='user_quests')
    op.drop_index(op.f('ix_user_quests_template'), table_name='user_quests')
    op.drop_index(op.f('ix_user_quests_user'), table_name='user_quests')
    op.create_index(op.f('ix_user_quests_template_id'), 'user_quests', ['template_id'], unique=False)
    op.create_index(op.f('ix_user_quests_user_id'), 'user_quests', ['user_id'], unique=False)
    op.create_index(op.f('ix_xp_events_id'), 'xp_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_events_id'), table_name='xp_events')
    op.drop_index(op.f('ix_user_quests_user_id'), table_name='user_quests')
    op.drop_index(op.f('ix_user_quests_template_id'), table_name='user_quests')
    op.create_index(op.f('ix_user_quests_user'), 'user_quests', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_quests_template'), 'user_quests', ['template_id'], unique=False)
    op.create_index(op.f('ix_user_quests_status'), 'user_quests', ['status'], unique=False)
    op.add_column('routines', sa.Column('source_routine_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_routines_source_routine_id_routines'), 'routines', 'routines', ['source_routine_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_quest_templates_code'), 'quest_templates', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_personal_best_events_id'), table_name='personal_best_events')
    op.create_index(op.f('ix_personal_best_events_user_created_at'), 'personal_best_events', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_bodyweight_calibrations_scenario_id'), table_name='bodyweight_calibrations')
    # ### end Alembic commands ###
