"""Add display_name to User model

Revision ID: 4cf0ad3ef629
Revises: b01619dda436
Create Date: 2025-07-17 08:49:39.047090

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cf0ad3ef629"
down_revision: Union[str, Sequence[str], None] = "b01619dda436"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('channels', 'guild_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    op.add_column(
        "users", sa.Column("display_name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "display_name")
    # op.alter_column('channels', 'guild_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # ### end Alembic commands ###
