"""Add subscription_level to User

Revision ID: 4dc1267d28ee
Revises: e43752880d87
Create Date: 2025-08-01 13:10:30.920351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc1267d28ee'
down_revision: Union[str, Sequence[str], None] = 'e43752880d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_level', sa.String(length=32), server_default='free', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_level')
    # ### end Alembic commands ###
