"""Add weight_multiplier to User

Revision ID: 5525a0ab4d2c
Revises: bab751eef8a4
Create Date: 2025-07-21 14:48:36.815899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5525a0ab4d2c'
down_revision: Union[str, Sequence[str], None] = 'bab751eef8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight_multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_multiplier')
    # ### end Alembic commands ###
