"""Make user_id nullable in routines

Revision ID: 567a1813c628
Revises: 1612bc0dc4c9
Create Date: 2025-07-07 17:43:53.653802

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "567a1813c628"
down_revision: Union[str, Sequence[str], None] = "1612bc0dc4c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("routines", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("routines", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
