"""Add cascade delete to scores

Revision ID: 58871d166ad3
Revises: 655e228aa20b
Create Date: 2025-08-26 07:43:35.186264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58871d166ad3'
down_revision: Union[str, Sequence[str], None] = '655e228aa20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scores_user_id_fkey'), 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key(op.f('scores_user_id_fkey'), 'scores', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
