"""add_is_bodyweight_to_scores

Revision ID: 655e228aa20b
Revises: ef46f42c0d12
Create Date: 2025-08-24 10:49:45.259791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655e228aa20b'
down_revision: Union[str, Sequence[str], None] = 'ef46f42c0d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('is_bodyweight', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'is_bodyweight')
    # ### end Alembic commands ###
