"""Add ON DELETE CASCADE to routine_scenario_submission.routine_id

Revision ID: 66440372a91f
Revises: f98b5ef5e896
Create Date: 2025-09-08 09:53:47.748129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66440372a91f'
down_revision: Union[str, Sequence[str], None] = 'f98b5ef5e896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('routine_scenario_submission_routine_id_fkey'), 'routine_scenario_submission', type_='foreignkey')
    op.create_foreign_key(None, 'routine_scenario_submission', 'routine_submission', ['routine_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routine_scenario_submission', type_='foreignkey')
    op.create_foreign_key(op.f('routine_scenario_submission_routine_id_fkey'), 'routine_scenario_submission', 'routine_submission', ['routine_id'], ['id'])
    # ### end Alembic commands ###
