"""Add rank column to users table

Revision ID: 6a6a97464f11
Revises: 76af191eee34
Create Date: 2025-08-28 12:46:45.445549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6a97464f11'
down_revision: Union[str, Sequence[str], None] = '76af191eee34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', sa.String(length=50), server_default='Unranked', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rank')
    # ### end Alembic commands ###
