"""Add payment provider IDs to User model

Revision ID: 756b17c5ecf7
Revises: af3a6aa533eb
Create Date: 2025-08-11 10:43:21.186477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756b17c5ecf7'
down_revision: Union[str, Sequence[str], None] = 'af3a6aa533eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('apple_original_transaction_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_apple_original_transaction_id'), 'users', ['apple_original_transaction_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_unique_constraint(None, 'users', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_apple_original_transaction_id'), table_name='users')
    op.drop_column('users', 'apple_original_transaction_id')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
