"""Add cascade delete to routine

Revision ID: 75be7a70107d
Revises: 58871d166ad3
Create Date: 2025-08-26 07:45:30.499843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75be7a70107d'
down_revision: Union[str, Sequence[str], None] = '58871d166ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('routines_user_id_fkey'), 'routines', type_='foreignkey')
    op.create_foreign_key(None, 'routines', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routines', type_='foreignkey')
    op.create_foreign_key(op.f('routines_user_id_fkey'), 'routines', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
