"""Add cascade delete to routine_scenario

Revision ID: 76af191eee34
Revises: 75be7a70107d
Create Date: 2025-08-26 07:47:00.067476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76af191eee34'
down_revision: Union[str, Sequence[str], None] = '75be7a70107d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('routine_scenario_association_routine_id_fkey'), 'routine_scenario_association', type_='foreignkey')
    op.drop_constraint(op.f('routine_scenario_association_scenario_id_fkey'), 'routine_scenario_association', type_='foreignkey')
    op.create_foreign_key(None, 'routine_scenario_association', 'routines', ['routine_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'routine_scenario_association', 'scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routine_scenario_association', type_='foreignkey')
    op.drop_constraint(None, 'routine_scenario_association', type_='foreignkey')
    op.create_foreign_key(op.f('routine_scenario_association_scenario_id_fkey'), 'routine_scenario_association', 'scenarios', ['scenario_id'], ['id'])
    op.create_foreign_key(op.f('routine_scenario_association_routine_id_fkey'), 'routine_scenario_association', 'routines', ['routine_id'], ['id'])
    # ### end Alembic commands ###
