"""add preferred_unit to users

Revision ID: 7cce11dcf858
Revises: 9093d133078a
Create Date: 2025-09-13 14:55:07.604764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cce11dcf858'
down_revision: Union[str, Sequence[str], None] = '9093d133078a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_unit', sa.String(length=3), server_default='kg', nullable=False))
    op.create_index(op.f('ix_users_preferred_unit'), 'users', ['preferred_unit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_preferred_unit'), table_name='users')
    op.drop_column('users', 'preferred_unit')
    # ### end Alembic commands ###
