"""Use Strings instead of UUID for scenarios

Revision ID: 85cfd907e22d
Revises: 4cf0ad3ef629
Create Date: 2025-07-17 18:32:58.012116

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85cfd907e22d"
down_revision: Union[str, Sequence[str], None] = "4cf0ad3ef629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenarios_id"), "scenarios", ["id"], unique=True)
    op.create_index(op.f("ix_scenarios_name"), "scenarios", ["name"], unique=True)
    op.create_table(
        "leaderboard_entries",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.String(), nullable=False),
        sa.Column("weight_lifted", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leaderboard_entries_id"), "leaderboard_entries", ["id"], unique=False
    )
    op.alter_column(
        "routine_scenario_association",
        "scenario_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "routine_scenario_association", "scenarios", ["scenario_id"], ["id"]
    )
    op.alter_column(
        "scores",
        "scenario_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "scores", "scenarios", ["scenario_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scores", type_="foreignkey")
    op.alter_column(
        "scores",
        "scenario_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "routine_scenario_association", type_="foreignkey")
    op.alter_column(
        "routine_scenario_association",
        "scenario_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_leaderboard_entries_id"), table_name="leaderboard_entries")
    op.drop_table("leaderboard_entries")
    op.drop_index(op.f("ix_scenarios_name"), table_name="scenarios")
    op.drop_index(op.f("ix_scenarios_id"), table_name="scenarios")
    op.drop_table("scenarios")
    # ### end Alembic commands ###
