"""Add muscles worked table called muscles

Revision ID: 870ab40d8939
Revises: 5525a0ab4d2c
Create Date: 2025-07-22 11:29:20.425388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870ab40d8939'
down_revision: Union[str, Sequence[str], None] = '5525a0ab4d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscles_id'), 'muscles', ['id'], unique=True)
    op.create_index(op.f('ix_muscles_name'), 'muscles', ['name'], unique=False)
    op.create_table('scenario_muscle_association',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('muscle_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('scenario_id', 'muscle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_muscle_association')
    op.drop_index(op.f('ix_muscles_name'), table_name='muscles')
    op.drop_index(op.f('ix_muscles_id'), table_name='muscles')
    op.drop_table('muscles')
    # ### end Alembic commands ###
