"""add bodyweight_calibrations table

Revision ID: 8c7dded74a36
Revises: 9d012face23f
Create Date: 2025-09-18 12:37:57.280577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7dded74a36'
down_revision: Union[str, Sequence[str], None] = '9d012face23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bodyweight_calibrations',
        sa.Column('scenario_id', sa.String(), nullable=False),
        sa.Column('beginner_50', sa.Integer(), nullable=False),
        sa.Column('elite_50', sa.Integer(), nullable=False),
        sa.Column('beginner_140', sa.Integer(), nullable=False),
        sa.Column('elite_140', sa.Integer(), nullable=False),
        sa.Column('intermediate_95', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('scenario_id')
    )

    # (Optional) If you want a data hygiene guard, uncomment this:
    # op.create_check_constraint(
    #     'ck_bodyweight_calibrations_nonneg',
    #     'bodyweight_calibrations',
    #     'beginner_50 >= 0 AND elite_50 >= 0 '
    #     'AND beginner_140 >= 0 AND elite_140 >= 0 '
    #     'AND intermediate_95 >= 0'
    # )

    # Drop staging tables/indexes if you're done with them
    op.drop_table('scenarios_backup')
    op.drop_index(op.f('scenarios_copy_id_idx'), table_name='scenarios_copy')
    op.drop_index(op.f('scenarios_copy_name_idx'), table_name='scenarios_copy')
    op.drop_table('scenarios_copy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'scenarios_copy',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column('is_bodyweight', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
        sa.Column('volume_multiplier', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('scenarios_copy_pkey'))
    )
    op.create_index(op.f('scenarios_copy_name_idx'), 'scenarios_copy', ['name'], unique=True)
    op.create_index(op.f('scenarios_copy_id_idx'), 'scenarios_copy', ['id'], unique=True)

    op.create_table(
        'scenarios_backup',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('is_bodyweight', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column('volume_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )

    # No need to drop a PK index on bodyweight_calibrations.scenario_id; none was created
    op.drop_table('bodyweight_calibrations')
    # ### end Alembic commands ###
