"""Rename apple_original_transaction_id to original_transaction_id

Revision ID: 9093d133078a
Revises: 66440372a91f
Create Date: 2025-09-08 10:25:01.138594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9093d133078a'
down_revision: Union[str, Sequence[str], None] = '66440372a91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('original_transaction_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_apple_original_transaction_id'), table_name='users')
    op.create_index(op.f('ix_users_original_transaction_id'), 'users', ['original_transaction_id'], unique=True)
    op.drop_column('users', 'apple_original_transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apple_original_transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_original_transaction_id'), table_name='users')
    op.create_index(op.f('ix_users_apple_original_transaction_id'), 'users', ['apple_original_transaction_id'], unique=True)
    op.drop_column('users', 'original_transaction_id')
    # ### end Alembic commands ###
