"""Add multiplier to scenario

Revision ID: 91e2179b2485
Revises: 8b369921a38d
Create Date: 2025-07-22 18:45:04.509737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e2179b2485'
down_revision: Union[str, Sequence[str], None] = '8b369921a38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_equipment_association',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('scenario_id', 'equipment_id')
    )
    op.create_table('scenario_primary_muscle_association',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('muscle_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('scenario_id', 'muscle_id')
    )
    op.create_table('scenario_secondary_muscle_association',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('muscle_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('scenario_id', 'muscle_id')
    )
    op.add_column('scenarios', sa.Column('multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'multiplier')
    op.drop_table('scenario_secondary_muscle_association')
    op.drop_table('scenario_primary_muscle_association')
    op.drop_table('scenario_equipment_association')
    # ### end Alembic commands ###
