"""Remove messages and channels tables

Revision ID: 924f739c6282
Revises: c7bea71d00c1
Create Date: 2025-08-20 12:44:59.616192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '924f739c6282'
down_revision: Union[str, Sequence[str], None] = 'c7bea71d00c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # MOVED UP: Must drop the dependent table ('messages') first.
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    
    # NOW it is safe to drop the table it depended on.
    op.drop_table('channels')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # MOVED UP: Must create the table that is a dependency ('channels') first.
    op.create_table('channels',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('guild_id', sa.UUID(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('channels_guild_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('channels_pkey'))
    )
    
    # NOW it is safe to create the table that depends on it.
    op.create_table('messages',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('channel_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('messages_author_id_fkey')),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('messages_channel_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    
    # ### end Alembic commands ###
