"""Add primary and secondary muscles worked

Revision ID: 99827472ff1f
Revises: 870ab40d8939
Create Date: 2025-07-22 11:45:51.010837

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99827472ff1f"
down_revision: Union[str, Sequence[str], None] = "870ab40d8939"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario_muscle_association",
        sa.Column("muscle_type", sa.String(), nullable=False, server_default="primary"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenario_muscle_association", "muscle_type")
    # ### end Alembic commands ###
