"""Add is_bodyweight to scenarios

Revision ID: 9e5c479a145c
Revises: 756b17c5ecf7
Create Date: 2025-08-14 18:44:04.897567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5c479a145c'
down_revision: Union[str, Sequence[str], None] = '756b17c5ecf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('is_bodyweight', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'is_bodyweight')
    # ### end Alembic commands ###
