"""make energy nullable

Revision ID: af3a6aa533eb
Revises: 4dc1267d28ee
Create Date: 2025-08-05 12:21:29.462736

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af3a6aa533eb"
down_revision: Union[str, Sequence[str], None] = "4dc1267d28ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("energy", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "energy")
    # ### end Alembic commands ###
