"""Make guild_id optional in channels

Revision ID: b01619dda436
Revises: c8999db9d7ad
Create Date: 2025-07-12 15:55:50.998264

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b01619dda436"
down_revision: Union[str, Sequence[str], None] = "c8999db9d7ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("channels", "guild_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("channels", "guild_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
