"""Add volume_multiplier to scenarios

Revision ID: c7bea71d00c1
Revises: 9e5c479a145c
Create Date: 2025-08-14 19:07:48.577476

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7bea71d00c1"
down_revision: Union[str, Sequence[str], None] = "9e5c479a145c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenarios",
        sa.Column(
            "volume_multiplier", sa.Float(), server_default="1.0", nullable=False
        ),
    )
    op.alter_column(
        "scenarios",
        "multiplier",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scenarios",
        "multiplier",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_column("scenarios", "volume_multiplier")
    # ### end Alembic commands ###
