"""Add ON DELETE CASCADE to energy_history

Revision ID: c8999db9d7ad
Revises: efba6dbfe25d
Create Date: 2025-07-12 09:40:06.811533

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8999db9d7ad"
down_revision: Union[str, Sequence[str], None] = "efba6dbfe25d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("energy_history_user_id_fkey"), "energy_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "energy_history", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "energy_history", type_="foreignkey")
    op.create_foreign_key(
        op.f("energy_history_user_id_fkey"),
        "energy_history",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
