"""Add routine model

Revision ID: d01eca8fff87
Revises: 5228e7241621
Create Date: 2025-07-07 11:49:25.866771

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d01eca8fff87"
down_revision: Union[str, Sequence[str], None] = "5228e7241621"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routines",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routines_id"), "routines", ["id"], unique=False)
    op.create_table(
        "routine_scenario_association",
        sa.Column("routine_id", sa.UUID(), nullable=True),
        sa.Column("scenario_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["routine_id"],
            ["routines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
    )
    op.alter_column(
        "scores", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scores", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_table("routine_scenario_association")
    op.drop_index(op.f("ix_routines_id"), table_name="routines")
    op.drop_table("routines")
    # ### end Alembic commands ###
