"""Add title to RoutineSubmission

Revision ID: e43752880d87
Revises: 00e4322a352f
Create Date: 2025-07-28 16:08:23.672373

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e43752880d87"
down_revision: Union[str, Sequence[str], None] = "00e4322a352f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routine_submission",
        sa.Column(
            "title", sa.String(), nullable=False, server_default="Untitled Workout"
        ),
    )


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routine_submission", "title")
    # ### end Alembic commands ###
