"""Add score value to score.py

Revision ID: ef46f42c0d12
Revises: 924f739c6282
Create Date: 2025-08-23 13:55:05.300656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = 'ef46f42c0d12'
down_revision: Union[str, Sequence[str], None] = '924f739c6282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('score_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    
    # Data migration: Calculate and populate score_value using the same formula as Dart code
    connection = op.get_bind()
    scores_table = table(
        'scores',
        column('id', sa.Integer),
        column('weight_lifted', sa.Float),
        column('reps', sa.Integer),
        column('score_value', sa.Float)
    )
    
    # Fetch all existing scores
    scores = connection.execute(sa.select(
        scores_table.c.id,
        scores_table.c.weight_lifted,
        scores_table.c.reps
    )).fetchall()
    
    # Update each score with calculated one-rep max
    for score in scores:
        weight = score.weight_lifted
        reps = score.reps or 1  # Handle null reps by defaulting to 1
        
        # Use the same formula as the Dart calculateOneRepMax function
        if reps == 1:
            score_value = weight
        else:
            score_value = weight * (1 + reps / 30)
        
        connection.execute(
            scores_table.update()
            .where(scores_table.c.id == score.id)
            .values(score_value=score_value)
        )
    
    # Now set the column to NOT NULL after populating all values
    op.alter_column('scores', 'score_value', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'score_value')
    # ### end Alembic commands ###