"""Add FK to energy_history

Revision ID: efba6dbfe25d
Revises: f1991dfa051f
Create Date: 2025-07-09 15:36:03.941589

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efba6dbfe25d"
down_revision: Union[str, Sequence[str], None] = "f1991dfa051f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energy_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("energy", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_energy_history_id"), "energy_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_energy_history_user_id"), "energy_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_energy_history_user_id"), table_name="energy_history")
    op.drop_index(op.f("ix_energy_history_id"), table_name="energy_history")
    op.drop_table("energy_history")
    # ### end Alembic commands ###
